# Generated by Django 3.2.9 on 2022-05-03 21:06

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import store.processor


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Container')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Tag')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='Passwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('url', models.CharField(max_length=512, verbose_name='URL')),
                ('website', models.CharField(blank=True, max_length=512, null=True, verbose_name='Website')),
                ('value', django_cryptography.fields.encrypt(models.TextField(verbose_name='Value'))),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.container')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('tags', models.ManyToManyField(to='store.Tag')),
            ],
            bases=(models.Model, store.processor.XlsxReader),
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, null=True, verbose_name='Key')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('passwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.passwd')),
            ],
        ),
    ]
