# Generated by Django 3.2.9 on 2022-05-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_passwd_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwd',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
