# Generated by Django 3.2.9 on 2022-09-16 12:02

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220509_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPasswd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('shared_value', django_cryptography.fields.encrypt(models.TextField())),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('passwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.passwd')),
            ],
        ),
    ]
