# Generated by Django 3.2.9 on 2022-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sharedpasswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpasswd',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
