# Generated by Django 3.2.9 on 2022-09-29 21:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sharedpasswd_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FernetKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', django_cryptography.fields.encrypt(models.TextField())),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('current', models.BooleanField(default=True)),
            ],
        ),
    ]
