# Generated by Django 3.2.9 on 2022-09-30 12:02

from django.db import migrations

from support.functions import fernet_encrypt_string


def add_fernet_layer(apps, schema_editor):
    customer_model = apps.get_model("customers", "Customer")
    passwd_model = apps.get_model("store", "Passwd")
    for passwd in passwd_model.objects.all():
        passwd.value = fernet_encrypt_string(passwd.value)
        passwd.save()
    for customer in customer_model.objects.all():
        customer.test_passwd = fernet_encrypt_string(customer.test_passwd)
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220930_1105'),
    ]

    operations = [
        migrations.RunPython(add_fernet_layer)
    ]
