# Generated by Django 3.2.9 on 2022-10-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220930_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fernetkey',
            name='current',
        ),
    ]
