# Generated by Django 3.2.9 on 2022-05-03 21:06

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, verbose_name='Mobile')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('language', models.CharField(blank=True, max_length=8, null=True, verbose_name='Language')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
