# Generated by Django 3.2.9 on 2022-05-09 18:20

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test_passwd',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Test passwd')),
        ),
    ]
