# Generated by Django 3.2.9 on 2022-05-25 12:50

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_test_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('expire', models.DateTimeField()),
            ],
        ),
    ]