# Generated by Django 3.2.9 on 2022-05-25 12:50

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_test_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=customers.models.generate_code, max_length=6, verbose_name='recover code')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('expire', models.DateTimeField(default=customers.models.get_expire_time_code, verbose_name='expire datetime')),
            ],
            options={
                'verbose_name': 'Recover Code',
                'verbose_name_plural': 'Recover Codes',
            },
        ),
    ]
