# Generated by Django 3.2.9 on 2022-09-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_recovercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=32)),
                ('value', models.CharField(db_index=True, max_length=44)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='secret_key',
            field=models.CharField(db_index=True, max_length=88, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApiKeyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.apikey')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.permission')),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=172)),
                ('active', models.BooleanField(default=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.apikey')),
            ],
        ),
    ]
