# Generated by Django 3.2.9 on 2022-09-20 10:58
import base64
import uuid

from django.db import migrations


def populate_secrets(apps, schema_editor):
    customer_model = apps.get_model('customers', 'Customer')
    api_key_model = apps.get_model('customers', 'ApiKey')
    access_token_model = apps.get_model('customers', 'AccessToken')
    for customer in customer_model.objects.filter(secret_key__isnull=True):
        # assign default secret_key
        part_1 = uuid.uuid4().__str__()
        part_2 = uuid.uuid4().__str__()
        secret_key = base64.b64encode(
            f"{part_1}{part_2}".replace("-", "").encode()
        ).decode()
        customer.secret_key = secret_key
        customer.save()
        if not customer.apikey_set.exists():
            # create default ApiKey
            api_key = api_key_model.objects.create(customer=customer)
            api_key.value = base64.b64encode(uuid.uuid4().__str__().replace("-", "").encode()).decode()
            api_key.save()
            # create default AccessToken
            access_token = access_token_model.objects.create(api_key=api_key)
            part_1 = uuid.uuid4().__str__()
            part_2 = uuid.uuid4().__str__()
            part_3 = uuid.uuid4().__str__()
            part_4 = uuid.uuid4().__str__()
            value = base64.b64encode(f"{part_1}{part_2}{part_3}{part_4}".replace("-", "").encode()).decode()
            access_token.value = value
            access_token.save()
            api_key.accesstoken_set.exclude(pk=access_token.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20220920_1057'),
    ]

    operations = [
        migrations.RunPython(populate_secrets)
    ]
